// Auto-generated by Scripts/generate_mpv_bindings.rb — do not edit
import Foundation

public enum MPVPropertyGenerated: String, Sendable {
    case pause = "pause"
    case time_pos = "time-pos"
    case duration = "duration"
    case volume = "volume"
    case speed = "speed"
    case filename = "filename"
    case media_title = "media-title"
    case mute = "mute"
    case eof_reached = "eof-reached"
}

public enum MPVCommandGenerated: String, Sendable {
    case loadfile = "loadfile"
    case stop = "stop"
    case quit = "quit"
    case seek = "seek"
    case cycle = "cycle"
    case set = "set"
    case show_text = "show-text"
    case sub_add = "sub-add"
    case sub_remove = "sub-remove"
    case playlist_next = "playlist-next"
    case playlist_prev = "playlist-prev"
}

public enum MPVOptionGenerated: String, Sendable {
    case vo = "vo"
    case hwdec = "hwdec"
    case keep_open = "keep-open"
    case hr_seek = "hr-seek"
    case sub_auto = "sub-auto"
    case sub_font_size = "sub-font-size"
    case ytdl = "ytdl"
    case input_default_bindings = "input-default-bindings"
    case input_vo_keyboard = "input-vo-keyboard"
}
